PROJECT         := LED_board
DEVICES         := NUCLEO_F401RE
GCC4MBED_DIR    := $(GCC4MBED_DIR)
#如果是在windows系统下，则需要改成   GCC4MBED_DIR    := ../..
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
